[package]
name = "serde_errors"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Path to the element that failed to deserialize"
repository = "https://github.com/dtolnay/serde-errors"
edition = "2018"

[dependencies]
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"

[badges]
travis-ci = { repository = "dtolnay/serde-errors" }
